apiVersion: v1
data:
  APP_DEBUG: dHJ1ZQ==
  APP_ENV: bG9jYWw=
  APP_KEY: YmFzZTY0OjRva3ZjK1ArNkFrdXhwVEpLU3BjYi9xYnBZZG9LOHFRTDZvY1hCWCtjbEk9
  APP_LOG_LEVEL: ZGVidWc=
  APP_NAME: TGFyYXZlbA==
  APP_URL: aHR0cDovL2xvY2FsaG9zdA==
  BROADCAST_DRIVER: bG9n
  CACHE_DRIVER: cmVkaXM=
  DB_CONNECTION: bXlzcWw=
  DB_DATABASE: bXlzcWx1c2VyZGI=
  DB_HOST: bXlzcWw=
  DB_PASSWORD: bXlzcWx1c2VycGFzcw==
  DB_PORT: MzMwNg==
  DB_USERNAME: bXlzcWx1c2Vy
  MAIL_DRIVER: c210cA==
  MAIL_ENCRYPTION: bnVsbA==
  MAIL_HOST: c210cC5tYWlsdHJhcC5pbw==
  MAIL_PASSWORD: bnVsbA==
  MAIL_PORT: MjUyNQ==
  MAIL_USERNAME: bnVsbA==
  PUSHER_APP_CLUSTER: bXQx
  PUSHER_APP_ID: ""
  PUSHER_APP_KEY: ""
  PUSHER_APP_SECRET: ""
  QUEUE_DRIVER: cmVkaXM=
  REDIS_HOST: cmVkaXM=
  REDIS_PASSWORD: cmVkaXNwYXNz
  REDIS_PORT: NjM3OQ==
  SESSION_DRIVER: ZGF0YWJhc2U=
  SESSION_LIFETIME: MTIw
kind: Secret
metadata:
  creationTimestamp: null
  name: env-secrets
